/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as CCourseSlugRouteImport } from './routes/c/$courseSlug'
import { Route as CourseSlugRouteImport } from './routes/course/$slug'
import { Route as OfficeIndexRouteImport } from './routes/office/index'
import { Route as OfficeSlugRouteImport } from './routes/office/$slug'
import { Route as OfficeNewRouteImport } from './routes/office/new'
import { Route as OfficeStudentsRouteImport } from './routes/office/students'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CCourseSlugIndexRouteImport } from './routes/c/$courseSlug/index'
import { Route as CCourseSlugCertificateRouteImport } from './routes/c/$courseSlug/certificate'
import { Route as CCourseSlugDeskRouteImport } from './routes/c/$courseSlug/desk'
import { Route as CCourseSlugExamRouteImport } from './routes/c/$courseSlug/exam'
import { Route as CCourseSlugSSlugRouteImport } from './routes/c/$courseSlug/s/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const CCourseSlugRoute = CCourseSlugRouteImport.update({
  id: '/c/$courseSlug',
  path: '/c/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseSlugRoute = CourseSlugRouteImport.update({
  id: '/course/$slug',
  path: '/course/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/office/',
  path: '/office/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeSlugRoute = OfficeSlugRouteImport.update({
  id: '/office/$slug',
  path: '/office/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeNewRoute = OfficeNewRouteImport.update({
  id: '/office/new',
  path: '/office/new',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeStudentsRoute = OfficeStudentsRouteImport.update({
  id: '/office/students',
  path: '/office/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CCourseSlugIndexRoute = CCourseSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCourseSlugRoute,
} as any)
const CCourseSlugCertificateRoute = CCourseSlugCertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => CCourseSlugRoute,
} as any)
const CCourseSlugDeskRoute = CCourseSlugDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => CCourseSlugRoute,
} as any)
const CCourseSlugExamRoute = CCourseSlugExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => CCourseSlugRoute,
} as any)
const CCourseSlugSSlugRoute = CCourseSlugSSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => CCourseSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/desk': typeof DeskRoute
  '/exam': typeof ExamRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/c/$courseSlug': typeof CCourseSlugRouteWithChildren
  '/course/$slug': typeof CourseSlugRoute
  '/office/$slug': typeof OfficeSlugRoute
  '/office/new': typeof OfficeNewRoute
  '/office/students': typeof OfficeStudentsRoute
  '/office/': typeof OfficeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$courseSlug/certificate': typeof CCourseSlugCertificateRoute
  '/c/$courseSlug/desk': typeof CCourseSlugDeskRoute
  '/c/$courseSlug/exam': typeof CCourseSlugExamRoute
  '/c/$courseSlug/': typeof CCourseSlugIndexRoute
  '/c/$courseSlug/s/$slug': typeof CCourseSlugSSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/desk': typeof DeskRoute
  '/exam': typeof ExamRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/course/$slug': typeof CourseSlugRoute
  '/office/$slug': typeof OfficeSlugRoute
  '/office/new': typeof OfficeNewRoute
  '/office/students': typeof OfficeStudentsRoute
  '/office': typeof OfficeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$courseSlug/certificate': typeof CCourseSlugCertificateRoute
  '/c/$courseSlug/desk': typeof CCourseSlugDeskRoute
  '/c/$courseSlug/exam': typeof CCourseSlugExamRoute
  '/c/$courseSlug': typeof CCourseSlugIndexRoute
  '/c/$courseSlug/s/$slug': typeof CCourseSlugSSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/desk': typeof DeskRoute
  '/exam': typeof ExamRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof DashboardRoute
  '/inbox': typeof InboxRoute
  '/c/$courseSlug': typeof CCourseSlugRouteWithChildren
  '/course/$slug': typeof CourseSlugRoute
  '/office/$slug': typeof OfficeSlugRoute
  '/office/new': typeof OfficeNewRoute
  '/office/students': typeof OfficeStudentsRoute
  '/office/': typeof OfficeIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/c/$courseSlug/certificate': typeof CCourseSlugCertificateRoute
  '/c/$courseSlug/desk': typeof CCourseSlugDeskRoute
  '/c/$courseSlug/exam': typeof CCourseSlugExamRoute
  '/c/$courseSlug/': typeof CCourseSlugIndexRoute
  '/c/$courseSlug/s/$slug': typeof CCourseSlugSSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificate'
    | '/desk'
    | '/exam'
    | '/login'
    | '/dashboard'
    | '/inbox'
    | '/c/$courseSlug'
    | '/course/$slug'
    | '/office/$slug'
    | '/office/new'
    | '/office/students'
    | '/office/'
    | '/api/auth/$'
    | '/c/$courseSlug/certificate'
    | '/c/$courseSlug/desk'
    | '/c/$courseSlug/exam'
    | '/c/$courseSlug/'
    | '/c/$courseSlug/s/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/desk'
    | '/exam'
    | '/login'
    | '/dashboard'
    | '/inbox'
    | '/course/$slug'
    | '/office/$slug'
    | '/office/new'
    | '/office/students'
    | '/office'
    | '/api/auth/$'
    | '/c/$courseSlug/certificate'
    | '/c/$courseSlug/desk'
    | '/c/$courseSlug/exam'
    | '/c/$courseSlug'
    | '/c/$courseSlug/s/$slug'
  id:
    | '__root__'
    | '/'
    | '/certificate'
    | '/desk'
    | '/exam'
    | '/login'
    | '/dashboard'
    | '/inbox'
    | '/c/$courseSlug'
    | '/course/$slug'
    | '/office/$slug'
    | '/office/new'
    | '/office/students'
    | '/office/'
    | '/api/auth/$'
    | '/c/$courseSlug/certificate'
    | '/c/$courseSlug/desk'
    | '/c/$courseSlug/exam'
    | '/c/$courseSlug/'
    | '/c/$courseSlug/s/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificateRoute: typeof CertificateRoute
  DeskRoute: typeof DeskRoute
  ExamRoute: typeof ExamRoute
  LoginRoute: typeof LoginRoute
  DashboardRoute: typeof DashboardRoute
  InboxRoute: typeof InboxRoute
  CCourseSlugRoute: typeof CCourseSlugRouteWithChildren
  CourseSlugRoute: typeof CourseSlugRoute
  OfficeSlugRoute: typeof OfficeSlugRoute
  OfficeNewRoute: typeof OfficeNewRoute
  OfficeStudentsRoute: typeof OfficeStudentsRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$courseSlug': {
      id: '/c/$courseSlug'
      path: '/c/$courseSlug'
      fullPath: '/c/$courseSlug'
      preLoaderRoute: typeof CCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$slug': {
      id: '/course/$slug'
      path: '/course/$slug'
      fullPath: '/course/$slug'
      preLoaderRoute: typeof CourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/office'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/$slug': {
      id: '/office/$slug'
      path: '/office/$slug'
      fullPath: '/office/$slug'
      preLoaderRoute: typeof OfficeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/new': {
      id: '/office/new'
      path: '/office/new'
      fullPath: '/office/new'
      preLoaderRoute: typeof OfficeNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/students': {
      id: '/office/students'
      path: '/office/students'
      fullPath: '/office/students'
      preLoaderRoute: typeof OfficeStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$courseSlug/': {
      id: '/c/$courseSlug/'
      path: '/'
      fullPath: '/c/$courseSlug/'
      preLoaderRoute: typeof CCourseSlugIndexRouteImport
      parentRoute: typeof CCourseSlugRoute
    }
    '/c/$courseSlug/certificate': {
      id: '/c/$courseSlug/certificate'
      path: '/certificate'
      fullPath: '/c/$courseSlug/certificate'
      preLoaderRoute: typeof CCourseSlugCertificateRouteImport
      parentRoute: typeof CCourseSlugRoute
    }
    '/c/$courseSlug/desk': {
      id: '/c/$courseSlug/desk'
      path: '/desk'
      fullPath: '/c/$courseSlug/desk'
      preLoaderRoute: typeof CCourseSlugDeskRouteImport
      parentRoute: typeof CCourseSlugRoute
    }
    '/c/$courseSlug/exam': {
      id: '/c/$courseSlug/exam'
      path: '/exam'
      fullPath: '/c/$courseSlug/exam'
      preLoaderRoute: typeof CCourseSlugExamRouteImport
      parentRoute: typeof CCourseSlugRoute
    }
    '/c/$courseSlug/s/$slug': {
      id: '/c/$courseSlug/s/$slug'
      path: '/s/$slug'
      fullPath: '/c/$courseSlug/s/$slug'
      preLoaderRoute: typeof CCourseSlugSSlugRouteImport
      parentRoute: typeof CCourseSlugRoute
    }
  }
}

interface CCourseSlugRouteChildren {
  CCourseSlugCertificateRoute: typeof CCourseSlugCertificateRoute
  CCourseSlugDeskRoute: typeof CCourseSlugDeskRoute
  CCourseSlugExamRoute: typeof CCourseSlugExamRoute
  CCourseSlugIndexRoute: typeof CCourseSlugIndexRoute
  CCourseSlugSSlugRoute: typeof CCourseSlugSSlugRoute
}

const CCourseSlugRouteChildren: CCourseSlugRouteChildren = {
  CCourseSlugCertificateRoute: CCourseSlugCertificateRoute,
  CCourseSlugDeskRoute: CCourseSlugDeskRoute,
  CCourseSlugExamRoute: CCourseSlugExamRoute,
  CCourseSlugIndexRoute: CCourseSlugIndexRoute,
  CCourseSlugSSlugRoute: CCourseSlugSSlugRoute,
}

const CCourseSlugRouteWithChildren = CCourseSlugRoute._addFileChildren(
  CCourseSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificateRoute: CertificateRoute,
  DeskRoute: DeskRoute,
  ExamRoute: ExamRoute,
  LoginRoute: LoginRoute,
  DashboardRoute: DashboardRoute,
  InboxRoute: InboxRoute,
  CCourseSlugRoute: CCourseSlugRouteWithChildren,
  CourseSlugRoute: CourseSlugRoute,
  OfficeSlugRoute: OfficeSlugRoute,
  OfficeNewRoute: OfficeNewRoute,
  OfficeStudentsRoute: OfficeStudentsRoute,
  OfficeIndexRoute: OfficeIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
